name: Publish Release

on:
  workflow_dispatch:
    inputs:
      connector:
        type: choice
        description: Select Connector
        required: true
        options:
          - api_inspectionlot_srv
          - api_inspectionplan_srv
          - api_masterinspcharacteristic_srv
          - api_inspectionmethod_srv
          - api_charcattributecatalog_srv
          - api_qualityinforecord_srv

jobs:
  call_workflow:
    name: Run Release Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/s4hana-release-template.yml@main
    secrets: inherit
    with:
      hana-connector-group: qm
      hana-connector-name: ${{ inputs.connector }}
